language: node_js
node_js: 7
script:
  - npm run build
branches:
  only:
    - master
    - /^v[0-9]/
cache:
  yarn: true
env:
  global:
    # CHROME_CLIENT_ID
    - secure: udW2TT+3nGbph1oHAGqIxEOuXkaM+M6oBy1l0IKm1IgX42XwH2y+xHmNlKcQS7hwsdgfdOgiRGL1k26PXMHHBpVjyaxpnQI1j7JTQIekORHEkTPlrBrICOF7iUOpwA9mq0PSnydRHf2x7H01hUZjBxblR8HcBJ3Azz8oJPGi7vG8hXh2IZUGal/6jaITuJ2XKCbNJ2VZI+dnaQT5Anfrem3QlHA46abZ3o/KCTVWyRs41bytLdcCr0k4QXHxwSD3OBgcTDPdnXe9fdFQXsMu+pxYVok8TEVoyCdoptMzqT7fVFirDRoubpaf8tup9Hs8fr9LWFlabZNTqRjjM+aIDO3ezZbVBP/7zsSYq3GUzlUtoFGM9Zdt7i13kaEGJUh/6Y6eyqaYW0ruZ7d8wAgoRwhMhB0660ksJfWHaNKV5F7XwXTmBVjiNWaLHRf/w592xfKKOxtVNAuWvIWY9m3wgvOLGsbZrjfMj+tmEvOGqPZCoYLJuxoXS7HiZun5VBkAcH5E+kIlN3kpenuZPEGtZleT2oQMfXu3WrX/RRFmMQioGU4lu6NIlpLMyRmBo1P7OqXPow0rQqPAbOCvsTG7BvGmrWoSKP+2IrBWtUM5XfcSss22WsGq5yeBh1a/5xkqWmh0+bOadTbxKs6df7ql+Z4/pv7gRA7/t6baegusKMA=
    # CHROME_CLIENT_SECRET
    - secure: F0AZi3lcMg9zCanT75zLUO6FddMF4czF72p2R40mxXm8oxtVWhxBgceqMJYkuFvYJTZQ55Gngo2cfzpSSzdoy/+s2OdW0POFF1tqcxSoTtJTOLNWfB+RcFCCUkrCJpVl/t8Q3p9cePwIUi+y0RQnRImzrbRBhLAtFpOlJHQvBKtBB78Q/3w0l+CwojOGPClhBbnwo59c88TDLGWw0LyhkPuqM+Bk+HTzHbMZE79KiyhDnuVXKjiXs2d7GvXA7+W8jOdqyqcfJIcc1N+jDrPb3PqSsT/i+gKOiifs+HoPTKXM6fPo0rTOGO5Mn3fSqQ13uJleAHAJxd0ww2EFFebgn/q1icuTWlUtu/tRbVZRxvHhQkrIM+KzKyPoOAqdvWiy7IOaBnlbFuGKjL8TbUkkCHNZsXmJpNAJCeaVDYH5e+sxxzrtn2Js4TYiWISIJ27SOZHV+uIj0IY34nmKlRg9u4OBtdNirhcghXIx7VD8Fx1FnLVzSvsi/1o49R1/29opz8Rk2GW9BA6caqWCsJ7aGbZLlfjkVtfAUlQN76QEUTHnfDariKlyy3u2kDN1v1Hi4TspI+/Fvii8mj38yCXulgX/lTujqrxp/DY+xO4GSO2TqFz5PS181cwRZ+QgLu9BvKMxXo2qD6xwR9Z/81on/AzzHW1fDuJMcaUZYFyb2Zw=
    # CHROME_REFRESH_TOKEN
    - secure: LkHoZ9hhq5/uZtmWbb249OYEN/sn6F8g+d8IIodY8784jGwZYJH24RAJY/jMNvk1tQuH6nPPgP09NS++F5L080gGKFvdP/B5YCSjxea+heoRpO2EzDy8M3wcvh2qqL66iAWk2aJo5y2TxoUo23WVLswqtE0l4tZIQXz1HPCjqQ3frSa8HFsFx56MuE9PpI7Mrs/Wlec4ga1l/kU7wIyAJk6aFbUqhEBU2SeakorXH0EarfUAv4HKM44HvXNo4nxWLiXdy6T2aU0uMlJemt9+OWmN3pqPFLQPxNeJT4jnGYdUSc1UUEDc1F8OCyJtX1RhJB2FgPUbhTEb/pABhY/oyiRM1G/+L9xPo9xDDxhdnxf7oROZk1eUBCg6ETS/Kp9dNTFjQWodeD4MF+Y5Y/WT2vTxurig3mJlUHLr+xnsRPwZopXrHXDZGCpdmBKLhLal2+/m+vCWqWu929QGp498g8uqVqOm60lWBT91kgF7DsI66QRe1LDZrrEPHi/PXHZjU8GcgjBdSi61kp9r+U+qnbKT3i/SVZf/8xGE7QLVQroE46ECjwM9+lG22zl091KGjUuFwGaYO85ZZSeWB/Hun1afUfRrRbu2YptVZg8vplhYSUKGRCkiQn4nbi0mRogT3AZXKzQqcPxi5ayjNemJf41QeCgfQ6MY6CHEtpat2YY=
deploy:
  - provider: script
    script: node deploy.js
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key:
      secure: RhxtszNnAdmu90OEKhXe2cvd7k8CRoqy1/iarzHep4bFsVx87NvHMJFsEVLcunNpnPoqpjoQQfcpJIfOwDZFx3kuYgmAb2giW58Y/AMKsi+d9MsI8bZeaFGL1SVk3H0mInyS9+qhLKiG4sZSo1VL7kaiZt9/7oaY+x+GtytYYp87TianWHV8s1U8hIiaGYyesGDsGAq/K6fZVAtZ6riGB0cuomB0q+JagXfTlAMmHd1Q3PZwczerbjbUI6CxDY4VKG0jk52Sg3s90QlMrfyN4INAaYnrvRQQ13Wd8Wc16H80zYhaST/oF2uuTU2KjZ2+zTIaZQs16TQMdGsCndYMhKEmvQgHkfZgY1bGug3d3Io7fgwZ0PXAN0sEgA9A4jcSSxtFqnciPubCio3RmFZB2gYML1ZwewHnVwKkIUSKb8Qw7Lle/69zZ91mb1DZp3DyvEquZtHgcp3UBG561MCy4ntm04Unrn8GN0opsEaWKyHnCUfMUuex21mCOKd7+kA6QBqecv3L/STSkaBQcwrw3ahKI4bbjNiUvjuRCOZwG7uidLaj0gXHd8H3DlHo6ckkErUZ+8PtcT6tQ15Vojg9ztfOTKGvXgFmH1yPCAXWd1xfF3ByZvdEWBrj0vB0SPvZgQEuTuSC6J13m427BBURUkgEDII8ifIVJdgnb8Q5/QI=
    file: dist/no-emoji.zip
    skip_cleanup: true
    on:
      tags: true
