language: node_js
node_js: 7
script:
  - npm run build
branches:
  only:
    - master
    - /^v[0-9]/
cache:
  yarn: true
deploy:
  - provider: script
    script: node deploy.js
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key:
      secure: RhxtszNnAdmu90OEKhXe2cvd7k8CRoqy1/iarzHep4bFsVx87NvHMJFsEVLcunNpnPoqpjoQQfcpJIfOwDZFx3kuYgmAb2giW58Y/AMKsi+d9MsI8bZeaFGL1SVk3H0mInyS9+qhLKiG4sZSo1VL7kaiZt9/7oaY+x+GtytYYp87TianWHV8s1U8hIiaGYyesGDsGAq/K6fZVAtZ6riGB0cuomB0q+JagXfTlAMmHd1Q3PZwczerbjbUI6CxDY4VKG0jk52Sg3s90QlMrfyN4INAaYnrvRQQ13Wd8Wc16H80zYhaST/oF2uuTU2KjZ2+zTIaZQs16TQMdGsCndYMhKEmvQgHkfZgY1bGug3d3Io7fgwZ0PXAN0sEgA9A4jcSSxtFqnciPubCio3RmFZB2gYML1ZwewHnVwKkIUSKb8Qw7Lle/69zZ91mb1DZp3DyvEquZtHgcp3UBG561MCy4ntm04Unrn8GN0opsEaWKyHnCUfMUuex21mCOKd7+kA6QBqecv3L/STSkaBQcwrw3ahKI4bbjNiUvjuRCOZwG7uidLaj0gXHd8H3DlHo6ckkErUZ+8PtcT6tQ15Vojg9ztfOTKGvXgFmH1yPCAXWd1xfF3ByZvdEWBrj0vB0SPvZgQEuTuSC6J13m427BBURUkgEDII8ifIVJdgnb8Q5/QI=
    file: dist/no-emoji.zip
    skip_cleanup: true
    on:
      tags: true
